# Generated by Django 3.2.9 on 2021-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BollywoodMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('actress', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HollywoodMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=50)),
                ('actress', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
